/*
 * Copyright (C) 2022-2026 by Christian Fischer
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

use crate::apu::apu_client::ApuClient;
use crate::apu::hpf::StereoHighPassFilters;
use crate::apu::sample::{SampleResult, StereoSample};
use crate::cpu::cpu::CPU_CLOCK_SPEED;
use crate::emulator_client::{EmulatorClient, EmulatorClientMut};
use crate::emulator_device::Clock;
use crate::utils::SerializableArray;
use core::cmp::min;

#[cfg(feature = "std")]
use std::fmt::{Display, Formatter};


/// The size of the sample buffer to be transmitted to the receiver of generated audio data.
pub const SAMPLE_BUFFER_SIZE: usize = crate::apu::apu_client::SAMPLE_BUFFER_SIZE;


/// Type alias for an array storing sample data generated by the APU.
type SampleBuffer = SerializableArray<StereoSample, SAMPLE_BUFFER_SIZE>;


/// Stores the configuration to initialize the audio generation.
pub struct AudioOutputSpec {
    pub sample_rate: u32,
}


/// Error codes occurred during audio output initialization.
#[cfg_attr(feature = "std", derive(Debug))]
pub enum AudioOutputSpecError {
    /// The requested sample rate is not supported.
    InvalidSampleRate,
}


/// A buffer object receiving the audio data generated by the APU.
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AudioOutput {
    /// The sample rate currently configured to generate audio data.
    sample_rate: u32,

    /// Records the time passed to check when to record a new sample.
    time_passed: Clock,

    /// Timestamp when the next sample has to be recorded.
    next_sample_time: Clock,

    /// The multiplier to be multiplied with the sample data
    /// in order to compute the average over n CPU cycles.
    sample_multiplier: f32,

    /// The current sample to be accumulated from sample data over n CPU cycles.
    current_sample: StereoSample,

    /// The buffer to record sample data and transfer them to the emulator frontend.
    buffer: SampleBuffer,

    /// The position where to insert the next sample.
    buffer_insert_pos: usize,

    /// Highpass filters for left and right channels to filter the output samples.
    high_pass_filter: StereoHighPassFilters,
}


impl AudioOutput {
    pub const DEFAULT_SAMPLE_RATE: u32 = 48_000;


    pub fn new(ec: &impl EmulatorClient) -> Self {
        Self {
            sample_rate:        Self::DEFAULT_SAMPLE_RATE,
            time_passed:        0,
            next_sample_time:   0,
            sample_multiplier:  0.0,
            current_sample:     StereoSample::default(),
            buffer:             [StereoSample::default(); SAMPLE_BUFFER_SIZE].into(),
            buffer_insert_pos:  0,
            high_pass_filter:   StereoHighPassFilters::new(ec),
        }
    }


    /// Set the [AudioOutputSpec] to be used for the audio output.
    pub fn set_audio_spec(&mut self, spec: AudioOutputSpec) -> Result<(), AudioOutputSpecError> {
        if spec.sample_rate > 0 {
            self.sample_rate = spec.sample_rate;
        }
        else {
            return Err(AudioOutputSpecError::InvalidSampleRate);
        }

        Ok(())
    }


    /// Get the sample rate configured for this output buffer.
    pub fn get_sample_rate(&self) -> u32 {
        self.sample_rate
    }


    /// Push a new sample into the buffer.
    /// Takes a sample as read from the APU channels and the number of cycles
    /// this sample was live.
    /// To produce sample data with the requested sample rate, the audio output will
    /// compute the average of all values within `CPU_CLOCK / sample rate` cycles.
    pub(crate) fn push(&mut self, ec: &mut impl EmulatorClientMut, sample: SampleResult<StereoSample>, cycles: Clock) {
        let mut remaining_cycles = cycles;

        while remaining_cycles > 0 {
            let time_to_next_sample = self.next_sample_time - self.time_passed;
            let run_cycles          = min(remaining_cycles, time_to_next_sample);

            // filter the sample data via high pass filter
            let sample_filtered = self.high_pass_filter.filter(sample);

            // sample data will be accumulated to produce the average value for one sample
            self.current_sample += sample_filtered * (run_cycles as f32) * self.sample_multiplier;

            // check if enough data collected to complete a sample
            self.time_passed += run_cycles;
            if self.time_passed >= self.next_sample_time {
                // write the sample into the buffer
                self.finish_sample(ec);

                // wrap after a second has passed to prevent an overflow
                if self.next_sample_time > CPU_CLOCK_SPEED {
                    self.next_sample_time -= CPU_CLOCK_SPEED;
                    self.time_passed -= CPU_CLOCK_SPEED;
                }

                // compute the time when the next sample has to be generated
                let sample_rate           = self.sample_rate as Clock;
                let last_sample_time      = self.next_sample_time;
                let current_sample_number = (self.next_sample_time + 1) * sample_rate / CPU_CLOCK_SPEED;
                let next_sample_number    = current_sample_number + 1;
                let next_sample_time      = next_sample_number * CPU_CLOCK_SPEED / sample_rate;
                self.next_sample_time     = next_sample_time;

                // compute a multiplier, the sample has to be multiplied with in order to get
                // the average over all values until this sample has been completed.
                let time_diff  = next_sample_time - last_sample_time;
                let multiplier = 1.0 / (time_diff as f32);
                self.sample_multiplier = multiplier;
            }

            remaining_cycles -= run_cycles;
        }
    }


    /// After collecting data for one sample, this pushes the current sample into the samples buffer
    /// and, if reached the end of the buffer, sends it to a receiver object.
    fn finish_sample(&mut self, ec: &mut impl EmulatorClientMut) {
        // store the sample on the current position inside the sample buffer
        self.buffer[self.buffer_insert_pos] = self.current_sample;

        // reset the sample accumulator
        self.current_sample = StereoSample::default();

        // increment the write position
        self.buffer_insert_pos += 1;

        // if we reached the end of the buffer ...
        if self.buffer_insert_pos >= SAMPLE_BUFFER_SIZE {
            // send it to the ApuClient
            ec.get_apu_client_mut().push_samples(&self.buffer);

            // and reset the insert position
            self.buffer_insert_pos = 0;
        }
    }
}


#[cfg(feature = "std")]
impl Display for AudioOutputSpecError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            AudioOutputSpecError::InvalidSampleRate => {
                write!(f, "Sample rate is not supported")
            }
        }
    }
}


#[cfg(feature = "std")]
impl std::error::Error for AudioOutputSpecError {
}
