[package]
name = "gemi-debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
eframe = { version = "0.29.1", default-features = false, features = [ "default_fonts", "glow", "persistence", ] }
egui = { version = "0.29.1", default-features = false }
egui_extras = { version = "0.29.1", default-features = false, features = [] }
egui_tiles = { version = "0.10.1", default-features = false, features = ["serde"] }
lazy_static = { version = "1.5.0", default-features = false, features = [] }
rfd = { version = "0.15.0", default-features = false, features = ["xdg-portal", "tokio"] }
serde = { version = "1.0.214", default-features = false, features = ["std", "derive"] }

# desktop:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = "0.3.31"

# wasm:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"


[dependencies.gemi-core]
path = "../../lib/core"
features = ["snapshots"]

[dependencies.gemi-utils]
path = "../../lib/utils"

