[package]
name = "gemi-core"
version = "0.1.0"
edition = "2021"

[dependencies]
flagset = { version = "0.4.6", default-features = false, features = [] }
serde = { version = "1.0.214", default-features = false, features = ["std"], optional = true }
zstd = { version = "0.13.2", default-features = false, features = [], optional = true }
base64 = { version = "0.22.1", default-features = false, features = ["std"], optional = true }

[dev-dependencies]
gemi-mock = { path = "../mock" }

[features]
default = []

# A feature to use the standard library. This may be disabled to support
# platforms with limited capabilities like embedded devices.
std = []

# Enables dynamic allocation support.
# This is required to hold larger data for memory to support cartridges > 32kiB
# and GameBoyColor support
dyn_alloc = []

# `file_io` adds functions to load and write RAM and ROM images from and into files.
# This is enabled by default and may be disabled for environments which do not
# support file access.
file_io = [
    "std",
    "dyn_alloc",
]

# Enables GameBoyColor support
# GBC requires additional memory, so disabling will reduce memory usage of the emulator
cgb = [
    "dyn_alloc",
]

# Enables the audio processing unit.
# Disabling will remove audio support and can be used to reduce executable size.
apu = [
    "std",
    "dyn_alloc",
]

# Enables support for serialisation/deserialisation using the "serde" crate
serde = [
    "std",
    "dyn_alloc",
    "flagset/serde",
    "dep:base64",
    "dep:serde",
    "dep:zstd",
]
